import { createHash, randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { createRemoteJWKSet, jwtVerify } from 'jose';
import type pg from 'pg';
import { PlatformError, requireScope, roleScopes, type Principal, type Role, type SessionInfo } from '../../platform-contracts/src/index.js';
import type { PostgresStore } from '../../persistence/src/index.js';
const scrypt=promisify(scryptCallback);
export const hashSecret=(value:string)=>createHash('sha256').update(value).digest('hex');
export async function hashPassword(password:string):Promise<string>{if(password.length<12||password.length>256)throw new PlatformError(400,'password_length','Use a password between 12 and 256 characters');const salt=randomBytes(16).toString('hex');const key=await scrypt(password,salt,64) as Buffer;return `scrypt:${salt}:${key.toString('hex')}`;}
export async function verifyPassword(password:string,encoded:string):Promise<boolean>{const [method,salt,hex]=encoded.split(':');if(method!=='scrypt'||!salt||!hex||password.length>256)return false;const actual=await scrypt(password,salt,64) as Buffer;const expected=Buffer.from(hex,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected);}
export interface OidcConfig {issuer:string;clientId:string;clientSecret?:string;redirectUri:string}
export interface IdentityConfig {secureCookies:boolean;setupToken?:string;oidc?:OidcConfig}
export interface Authenticated {principal:Principal;session?:SessionInfo;bearer:boolean;tokenHash?:string}
const cookieMap=(header:string|null)=>Object.fromEntries((header??'').split(';').map(v=>v.trim().split('=')).filter(v=>v.length===2));
const roles=['admin','builder','operator','viewer'];
export class IdentityService {
  constructor(private readonly store:PostgresStore,private readonly config:IdentityConfig){}
  private get pool():pg.Pool{return this.store.pool;}
  async setupRequired():Promise<boolean>{return !(await this.pool.query('SELECT 1 FROM users LIMIT 1')).rowCount;}
  async setup(input:{name:string;email:string;password:string;workspace:string;setupToken?:string}):Promise<{session:SessionInfo;cookies:string[]}> {
    if(this.config.setupToken&&hashSecret(input.setupToken??'')!==hashSecret(this.config.setupToken))throw new PlatformError(403,'setup_token_required','Enter the setup token configured for this installation');
    const passwordHash=await hashPassword(input.password);const email=this.email(input.email);const client=await this.pool.connect();const id=randomUUID();
    try{await client.query('BEGIN');await client.query("SELECT pg_advisory_xact_lock(hashtext('onto-first-admin'))");if((await client.query('SELECT 1 FROM users LIMIT 1')).rowCount)throw new PlatformError(409,'already_configured','This installation already has an administrator');
      await client.query('INSERT INTO tenants(id,name) VALUES($1,$2)',['default',this.name(input.workspace)]);
      await client.query("INSERT INTO users(id,tenant_id,name,email,password_hash,role) VALUES($1,'default',$2,$3,$4,'admin')",[id,this.name(input.name),email,passwordHash]);await client.query('COMMIT');
    }catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
    return this.newSession((await this.store.principal('default',id))!);
  }
  async checkRateLimit(key:string):Promise<void>{const r=await this.pool.query("INSERT INTO auth_attempts(key,count) VALUES($1,1) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN auth_attempts.window_at<now()-interval '15 minutes' THEN 1 ELSE auth_attempts.count+1 END,window_at=CASE WHEN auth_attempts.window_at<now()-interval '15 minutes' THEN now() ELSE auth_attempts.window_at END RETURNING count",[hashSecret(key)]);if(r.rows[0].count>15)throw new PlatformError(429,'rate_limited','Too many sign-in attempts. Try again in 15 minutes.');}
  async login(email:string,password:string):Promise<{session:SessionInfo;cookies:string[]}>{const row=(await this.pool.query('SELECT * FROM users WHERE email=$1 AND active=true',[this.email(email)])).rows[0];
    if(!row?.password_hash||!await verifyPassword(password,row.password_hash))throw new PlatformError(401,'invalid_credentials','Email or password is incorrect');const principal=(await this.store.principal(row.tenant_id,row.id))!;await this.store.audit(principal,'identity.signed_in',principal.actorId);return this.newSession(principal);
  }
  private async newSession(principal:Principal):Promise<{session:SessionInfo;cookies:string[]}>{const token=randomBytes(32).toString('base64url');const csrf=randomBytes(24).toString('base64url');await this.pool.query("INSERT INTO sessions(token_hash,user_id,csrf_hash,expires_at) VALUES($1,$2,$3,now()+interval '12 hours')",[hashSecret(token),principal.actorId,hashSecret(csrf)]);return {session:await this.sessionInfo(principal,csrf),cookies:[this.cookie('onto_session',token,true,43200),this.cookie('onto_csrf',csrf,false,43200)]};}
  private cookie(name:string,value:string,httpOnly:boolean,maxAge:number){return `${name}=${value}; Path=/; SameSite=Lax; Max-Age=${maxAge}${httpOnly?'; HttpOnly':''}${this.config.secureCookies?'; Secure':''}`;}
  async authenticate(request:Request):Promise<Authenticated|undefined>{const bearer=request.headers.get('authorization');if(bearer?.startsWith('Bearer ')){const row=(await this.pool.query('SELECT * FROM api_tokens WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>now()',[hashSecret(bearer.slice(7))])).rows[0];if(!row)return undefined;const p=await this.store.principal(row.tenant_id,row.user_id);if(!p)return undefined;return {principal:{...p,scopes:p.scopes.filter(s=>(row.scopes as string[]).includes(s))},bearer:true};}
    const cookies=cookieMap(request.headers.get('cookie'));if(!cookies.onto_session)return undefined;const tokenHash=hashSecret(cookies.onto_session);const row=(await this.pool.query('SELECT s.csrf_hash,u.tenant_id,u.id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND u.active=true',[tokenHash])).rows[0];if(!row)return undefined;
    const principal=await this.store.principal(row.tenant_id,row.id);if(!principal)return undefined;const csrf=cookies.onto_csrf??'';if(hashSecret(csrf)!==row.csrf_hash)return undefined;return {principal,session:await this.sessionInfo(principal,csrf),bearer:false,tokenHash};
  }
  async sessionInfo(principal:Principal,csrfToken=''):Promise<SessionInfo>{const row=(await this.pool.query('SELECT name FROM tenants WHERE id=$1',[principal.tenantId])).rows[0];return {user:principal,csrfToken,authMode:this.config.oidc?'oidc':'local',tenant:{id:principal.tenantId,name:row?.name??principal.tenantId}};}
  async logout(auth:Authenticated):Promise<string[]>{if(auth.tokenHash)await this.pool.query('DELETE FROM sessions WHERE token_hash=$1',[auth.tokenHash]);return [this.cookie('onto_session','',true,0),this.cookie('onto_csrf','',false,0)];}
  assertCsrf(request:Request,auth:Authenticated){if(auth.bearer)return;if(!auth.session?.csrfToken||request.headers.get('x-csrf-token')!==auth.session.csrfToken)throw new PlatformError(403,'csrf_failed','Refresh the page before making this change');}
  async users(principal:Principal){requireScope(principal,'admin');return (await this.pool.query('SELECT id,name,email,role,active,created_at AS "createdAt" FROM users WHERE tenant_id=$1 ORDER BY created_at',[principal.tenantId])).rows;}
  async createUser(principal:Principal,input:{name:string;email:string;password?:string;role:Role}){requireScope(principal,'admin');if(!roles.includes(input.role))throw new PlatformError(400,'role_invalid','Choose a valid role');const id=randomUUID();const passwordHash=input.password?await hashPassword(input.password):null;if(!passwordHash&&!this.config.oidc)throw new PlatformError(400,'password_required','A password is required for local accounts');try{await this.pool.query('INSERT INTO users(id,tenant_id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5,$6)',[id,principal.tenantId,this.name(input.name),this.email(input.email),passwordHash,input.role]);}catch(e){if((e as {code?:string}).code==='23505')throw new PlatformError(409,'email_exists','That email already has an account');throw e;}await this.store.audit(principal,'identity.user_created',id,{role:input.role});return this.store.principal(principal.tenantId,id);}
  async updateUser(principal:Principal,id:string,input:{role?:Role;active?:boolean}){requireScope(principal,'admin');if(input.role&&!roles.includes(input.role))throw new PlatformError(400,'role_invalid','Choose a valid role');if(id===principal.actorId&&(input.active===false||input.role&&input.role!=='admin'))throw new PlatformError(409,'own_admin','Use another administrator to change your own administrator access');const result=await this.pool.query('UPDATE users SET role=COALESCE($3,role),active=COALESCE($4,active) WHERE tenant_id=$1 AND id=$2 RETURNING id,name,email,role,active',[principal.tenantId,id,input.role??null,input.active??null]);if(!result.rowCount)throw new PlatformError(404,'user_missing','User not found');await this.pool.query('DELETE FROM sessions WHERE user_id=$1',[id]);await this.store.audit(principal,'identity.user_updated',id,input);return result.rows[0];}
  async tokens(principal:Principal){return (await this.pool.query('SELECT id,name,scopes,expires_at AS "expiresAt",revoked_at AS "revokedAt",created_at AS "createdAt" FROM api_tokens WHERE tenant_id=$1 AND user_id=$2 ORDER BY created_at DESC',[principal.tenantId,principal.actorId])).rows;}
  async createToken(principal:Principal,input:{name:string;scopes:string[]}){if(!Array.isArray(input.scopes)||!input.scopes.length||input.scopes.some(s=>!principal.scopes.includes(s)))throw new PlatformError(403,'scope_escalation','Token scopes must be a subset of your current permissions');const token=`onto_${randomBytes(32).toString('base64url')}`;const id=randomUUID();await this.pool.query("INSERT INTO api_tokens(id,token_hash,tenant_id,user_id,name,scopes,expires_at) VALUES($1,$2,$3,$4,$5,$6,now()+interval '30 days')",[id,hashSecret(token),principal.tenantId,principal.actorId,this.name(input.name),JSON.stringify([...new Set(input.scopes)])]);await this.store.audit(principal,'identity.token_created',id,{scopes:input.scopes});return {id,token,expiresInDays:30};}
  async revokeToken(principal:Principal,id:string){await this.pool.query('UPDATE api_tokens SET revoked_at=now() WHERE tenant_id=$1 AND user_id=$2 AND id=$3',[principal.tenantId,principal.actorId,id]);await this.store.audit(principal,'identity.token_revoked',id);}
  oidcEnabled(){return !!this.config.oidc;}
  private async discovery(){const cfg=this.config.oidc;if(!cfg)throw new PlatformError(404,'oidc_unconfigured','Enterprise sign-in is not configured');if(!cfg.issuer.startsWith('https://'))throw new Error('OIDC issuer must use HTTPS');const response=await fetch(`${cfg.issuer.replace(/\/$/,'')}/.well-known/openid-configuration`,{signal:AbortSignal.timeout(10000),redirect:'error'});if(!response.ok)throw new Error('Identity discovery is unavailable');const data=await response.json() as Record<string,string>;if(data.issuer!==cfg.issuer||!['authorization_endpoint','token_endpoint','jwks_uri'].every(k=>data[k]?.startsWith('https://')))throw new Error('Identity discovery does not match configured issuer');return {cfg,data};}
  async oidcStart(){const {cfg,data}=await this.discovery();const state=randomBytes(32).toString('base64url'),verifier=randomBytes(48).toString('base64url'),nonce=randomBytes(32).toString('base64url');await this.pool.query("DELETE FROM oidc_states WHERE expires_at<now()");await this.pool.query("INSERT INTO oidc_states(state_hash,verifier,nonce,expires_at) VALUES($1,$2,$3,now()+interval '10 minutes')",[hashSecret(state),verifier,nonce]);const url=new URL(data.authorization_endpoint!);Object.entries({client_id:cfg.clientId,response_type:'code',redirect_uri:cfg.redirectUri,scope:'openid email profile',state,nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'}).forEach(([k,v])=>url.searchParams.set(k,v));return {url:url.toString(),cookie:this.cookie('onto_oidc',state,true,600)};}
  async oidcCallback(request:Request){const url=new URL(request.url),state=url.searchParams.get('state'),code=url.searchParams.get('code');if(!state||!code||cookieMap(request.headers.get('cookie')).onto_oidc!==state)throw new PlatformError(403,'oidc_state','Sign-in state is invalid or expired');const row=(await this.pool.query('DELETE FROM oidc_states WHERE state_hash=$1 AND expires_at>now() RETURNING verifier,nonce',[hashSecret(state)])).rows[0];if(!row)throw new PlatformError(403,'oidc_state','Sign-in state is invalid or expired');const {cfg,data}=await this.discovery();const body=new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:cfg.redirectUri,client_id:cfg.clientId,code_verifier:row.verifier,...(cfg.clientSecret?{client_secret:cfg.clientSecret}:{})});const response=await fetch(data.token_endpoint!,{method:'POST',body,signal:AbortSignal.timeout(10000),redirect:'error'});if(!response.ok)throw new PlatformError(401,'oidc_exchange','Enterprise sign-in could not be completed');const tokens=await response.json() as {id_token?:string};if(!tokens.id_token)throw new PlatformError(401,'oidc_token','Identity token is missing');const {payload}=await jwtVerify(tokens.id_token,createRemoteJWKSet(new URL(data.jwks_uri!)),{issuer:cfg.issuer,audience:cfg.clientId});if(payload.nonce!==row.nonce||payload.email_verified!==true||typeof payload.email!=='string'||!payload.sub)throw new PlatformError(401,'oidc_claims','Verified email and sign-in nonce are required');const user=(await this.pool.query('SELECT * FROM users WHERE email=$1 AND active=true',[this.email(payload.email)])).rows[0];if(!user)throw new PlatformError(403,'account_required','Ask your workspace administrator to create your account first');const subject=`${cfg.issuer}|${payload.sub}`;if(user.oidc_subject&&user.oidc_subject!==subject)throw new PlatformError(403,'subject_mismatch','Identity does not match this account');const bound=await this.pool.query('UPDATE users SET oidc_subject=$1 WHERE id=$2 AND active=true AND (oidc_subject IS NULL OR oidc_subject=$1) RETURNING id',[subject,user.id]);if(bound.rowCount!==1)throw new PlatformError(403,'subject_mismatch','Identity binding changed during sign-in');const principal=await this.store.principal(user.tenant_id,user.id);if(!principal)throw new PlatformError(403,'account_inactive','Account is no longer active');const result=await this.newSession(principal);result.cookies.push(this.cookie('onto_oidc','',true,0));return result;}
  private email(value:string){if(typeof value!=='string'||value.length>254||!/^\S+@\S+\.\S+$/.test(value))throw new PlatformError(400,'email_invalid','Enter a valid email address');return value.trim().toLowerCase();}
  private name(value:string){if(typeof value!=='string'||!value.trim()||value.length>160)throw new PlatformError(400,'name_invalid','Enter a name between 1 and 160 characters');return value.trim();}
}
